AWSTemplateFormatVersion: '2010-09-09'
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: bucket-bugtracker
      
  cloudfrontoriginaccessidentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: "OAI for bucket_bugtracker"
  CloudFrontDistributionBugTracker:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
        - Id: !Ref S3Bucket
          DomainName: !Ref S3Bucket
          S3OriginConfig:
            OriginAccessIdentity:  !Ref cloudfrontoriginaccessidentity
        Enabled: 'true'
        Comment: "Bugtracker Distribution"
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          AllowedMethods:
          - DELETE
          - GET
          - HEAD
          - OPTIONS
          - PATCH
          - POST
          - PUT
          TargetOriginId: !Ref S3Bucket
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none

          ViewerProtocolPolicy: allow-all

        ViewerCertificate:
          CloudFrontDefaultCertificate: 'true'    




   