AWSTemplateFormatVersion: '2010-09-09'
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
  cloudfrontoriginaccessidentity:
    Ref:  OAI_bugtracker
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: "OAI for bucket_bugtracker"
  CloudFrontDistributionBugTracker:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: bucket_bugtracker.s3.us-east-1.amazonaws.com
          Id: bucket_bugtracker
          S3OriginConfig:
            OriginAccessIdentity: OAI_bugtracker
        Enabled: 'true'
        Comment: "Bugtracker Distribution"
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          AllowedMethods:
          - DELETE
          - GET
          - HEAD
          - OPTIONS
          - PATCH
          - POST
          - PUT
          TargetOriginId: bucket_bugtracker
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none

          ViewerProtocolPolicy: allow-all

        ViewerCertificate:
          CloudFrontDefaultCertificate: 'true'    
Outputs:
  BucketName:
    Value: 'bucket_bugtracker'
    Description: static hosting for bugtracker



   