AWSTemplateFormatVersion: '2010-09-09'
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      WebsiteConfiguration: 
        IndexDocument: index.html
        ErrorDocument: index.html
      
  cloudfrontoriginaccessidentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: "OAI for bucket_bugtracker"
  CloudFrontDistributionBugTracker:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: !GetAtt  S3Bucket.RegionalDomainName
          Id: 'BugTracker'
          S3OriginConfig:
            OriginAccessIdentity: !GetAtt cloudfrontoriginaccessidentity.S3CanonicalUserId
        Enabled: 'true'
        Comment: "Bugtracker Distribution"
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          AllowedMethods:
          - DELETE
          - GET
          - HEAD
          - OPTIONS
          - PATCH
          - POST
          - PUT
          TargetOriginId: 'BugTracker'
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none

          ViewerProtocolPolicy: allow-all

        ViewerCertificate:
          CloudFrontDefaultCertificate: 'true'    




   